### ISSUE TITLE
The dotnet-preview image in Docker Hub wasn't rebuilt with CLI 1.0.0-beta-001876

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker-preview#4]
The CLI build for 1876 succeeded but there is no new build triggered in Docker Hub. Hand installing the CLI Debian package (https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-ubuntu-x64.latest.deb) yields a `dotnet --version` of 1.0.0-beta-001793 (ie an older version). Possibly there was an issue in the Debian package upload?

**Comment by MichaelSimons** [comment]
Looks like the condition was not met to trigger the docker hub builds.  The following line appears in the build log for ubuntu rel/1.0.0 - 2016-03-18T10:55:02.469Z: Skipping, Target Conditions not met: TriggerDockerHubBuilds.

**Comment by naamunds** [comment]
It looks like the issue is that the environment variables are not being flowed to the Docker container in which the build is run.  I've made a commit in my fork to address this, but it looks like the CLI Debian package was intentionally disabled (see https://github.com/dotnet/cli/commit/aa989f1e6edd4c72e81b0622e0e5655f857c42f0), so even with the trigger working, it wouldn't have the latest CLI installation.  I'm going to look into why the Deiban package publishing was disabled before making a PR for my change to trigger the builds.

**Comment by naamunds** [comment]
Disabling the publish of the CLI Debian packages is a temporary fix, as stated in https://github.com/dotnet/cli/pull/1947.  I've gone ahead and created a PR to fix the trigger of the DockerHub builds.

**Comment by naamunds** [comment]
Reopening this issue until it's been verified that DockerHub builds are properly triggered and have the latest CLI version.

**Comment by colemickens** [comment]
The `preview` container was tagged again today, but it's still 001793

**Comment by MichaelSimons** [comment]
The reason the images still reference 001793 is because of https://github.com/dotnet/cli/issues/2007.

**Comment by MichaelSimons** [comment]
This issue has been resolved.  The preview image build in Docker hub is getting triggered by the dotnet  CLI CI.  The latest Docker image contains the latest CLI build.
